version: '3.8'

services:
  opencv-jupyter:
    build: .
    image: tanyep/ubuntu20:jupyterlab.1
#    dockerfile: Dockerfile
    ports:
     - "8888:8888"
    volumes:
     - ./opencv:/home/opencv
    environment:
       - PASSWORD=sha1:09e8b4db7362:515d8c18822941989366ee0a2a2bed5b7e192f1f
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: "jupyter lab --allow-root --ip 0.0.0.0 --NotebookApp.password=${ACCESS_TOKEN}  "
